### ISSUE TITLE
Is the training model trustworthy?

### ISSUE THREAD

**Issue by ybsun0215** [guxd/deepAPI#10]
I downloaded the 120,000. model you trained in the dataset and tested it. The following results were obtained from 1000 test questions，
Avg Recall BLEU 34.955057, Avg Precision BLEU 34.955057, F1 34.955057，Is there a problem there?

**Comment by kongmoumou** [comment]
Hi~how long did u take to run the `sample.py`. It seems to need **23h** in my machine with 2080ti. Is it normal? Or there are something wrong with my environment 🤔. @ybsun0215 @guxd 
![image](https://user-images.githubusercontent.com/35442047/205638211-b1d2710f-5fc5-4afa-992a-1d52b77cc3fc.png)

**Comment by ybsun0215** [comment]
> Hi~how long did u take to run the `sample.py`. It seems to need **23h** in my machine with 2080ti. Is it normal? Or there are something wrong with my environment 🤔. @ybsun0215 @guxd ![image](https://user-images.githubusercontent.com/35442047/205638211-b1d2710f-5fc5-4afa-992a-1d52b77cc3fc.png)

Maybe it's normal, i remebered training it with 3090 for serveral hours (probably more than 5). However, the results seem not well.

**Comment by guxd** [comment]
The PyTorch replication is currently problematic. So it cannot achieve the original results in the paper.
