### ISSUE TITLE
How is the training set generated

### ISSUE THREAD

**Issue by Dawn-sir** [guxd/deepAPI#11]
Dear Professor Gu, I was wondering how the training set is generated? When I opened the 'train.apiseq.h5' file, there were two data sets: indices and phrases. What do they each represent? At the same time, the indices data set contains two attributes, length and pos. How is it generated? After I read the paper, I still couldn't understand it, which caused me a lot of trouble. I'm looking forward to get your reply sincerely. Thank you!
Here are some of the data sets I could see.
![image](https://user-images.githubusercontent.com/98569833/209474199-d86bf311-3e65-4505-bb89-71020b65f108.png)

**Comment by guxd** [comment]
Hi, you can refer to https://github.com/guxd/DialogBERT/blob/master/prepare_data.py, which processes texts into the same h5 format.

**Comment by Dawn-sir** [comment]
Thank you very much for your reply! Although I have solved the problem, I still benefit a lot from this reply.
