### ISSUE TITLE
Some typo errors in pytorch/sample.py line 35, lacking variable vocab?

### ISSUE THREAD

**Issue by ZhaoYi1031** [guxd/deepAPI#4]
I run the code, but encounter an error in Line35 in sample.py.

"name 'vocab' is not defined"

I checked that there seemed no variables named vocab, am i wrong or there existed some typo bugs?

(I am sorry I sent the same content in Pull requests part.

**Comment by guxd** [comment]
I refactorized the code significantly. The whole dataset is changed.  Please pull and re-download the dataset.
