### ISSUE TITLE
please provide accurate training data

### ISSUE THREAD

**Issue by Moshiii** [guxd/deepAPI#6]
Hello!

Thanks for your amazing work!
I am a researcher at york university and I am trying to reproduce your work. I found some problem here:

I am trying to extract training data from the h5 file using the data loader but I got non-sense labels:
![image](https://user-images.githubusercontent.com/7553188/96312222-28195200-0fd9-11eb-9ee0-385320dd7ad2.png)
I am sure that this is not a parsing error for the reason that:

The index matches the dictionary:
![image](https://user-images.githubusercontent.com/7553188/96322136-e9d65f80-0fe5-11eb-98cc-a70e99352c24.png)
dictionary:
![image](https://user-images.githubusercontent.com/7553188/96322172-083c5b00-0fe6-11eb-8733-4c7b92586a47.png)

I am using the original APIdata class
![image](https://user-images.githubusercontent.com/7553188/96310223-ec7c8900-0fd4-11eb-8c53-3adab988107d.png)
and  I decode the api answer using the original script:
![image](https://user-images.githubusercontent.com/7553188/96310328-2b124380-0fd5-11eb-8f3c-7ef13a1f80c3.png)

Please confirm this problem and upload the most recent valid dataset.  
My email is moshiwei@york.ca

Best,
Moshi

**Comment by guxd** [comment]
The default main function in the `data_loader.py` is deprecated. Please use the `indexes2sent` function from `help.py`. A demo can be found in Line28 and Line 36 at `sample.py`.

**Comment by Moshiii** [comment]
Awesome! it works! Also can you please share the trained model? my email is  moshiwei@york.ca

Regards,
Moshi
